name: ts
description: "A private photo gallery app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Network and API
  http: ^1.2.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  
  # UI Components
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  confetti: ^0.7.0
  
  # State Management
  provider: ^6.1.1
  
  # Storage and Caching
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  
  # Authentication
  local_auth: ^2.1.8
  
  # Audio
  audioplayers: ^5.2.1
  
  # Utils
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700